### ISSUE TITLE
NoMethodError: undefined method `configure' for RSpec:Module

### ISSUE THREAD

**Issue by ClaudioFloreani** [baban/flextures#23]
### Versions
- ruby 2.7.0p
- rails (6.0.3.4)
- activerecord 6.0.3.4
- activesupport 6.0.3.4
- flextures 4.3.0
- smarter_csv 1.2.6
- rspec-core (3.10.0)
- rspec-expectations (3.10.0)
- rspec-mocks (3.10.0)
- rspec-rails (4.0.1)
- rspec-support (3.10.0)

### Command
$ rails db:flextures:dump --trace

### Trace
```
rails aborted!
NoMethodError: undefined method `configure' for RSpec:Module
./.rvm/gems/ruby-2.7.0/gems/flextures-4.3.0/lib/flextures/rspec_flextures_support.rb:19:in `<module:RSpec>'
./.rvm/gems/ruby-2.7.0/gems/flextures-4.3.0/lib/flextures/rspec_flextures_support.rb:2:in `<main>'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
./.rvm/gems/ruby-2.7.0/gems/flextures-4.3.0/lib/flextures.rb:12:in `<main>'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
./.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
./.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:69:in `each'
./.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
./.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:58:in `each'
./.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:58:in `require'
./.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/bundler.rb:174:in `require'
./…/config/application.rb:20:in `<main>'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
./…/Rakefile:4:in `<main>'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
./.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
./.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
./.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
./.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
./.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
./.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
./.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
./.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
./.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
./.rvm/gems/ruby-2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
./.rvm/gems/ruby-2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
./.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
```

**Comment by ClaudioFloreani** [comment]
Missing gem dependency 'rspec-core'

**Comment by baban** [comment]
thanks message!
I'll fix it!
please wait!

**Comment by baban** [comment]
![Uploading image.png…]()

**Comment by baban** [comment]
I checked your report, but it dodn't reappere in my enviroment.
Flextures is cheking rspec install or not install when program get up.
https://github.com/baban/flextures/blob/master/lib/flextures.rb#L12
I guess that your report is quite rare.
